### ISSUE TITLE
0.2.2 release not posted

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/xarray_leaflet-feedstock#23]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Looks like the CI did not work https://github.com/conda-forge/xarray_leaflet-feedstock/pull/21 

Just hoping to use the conda-forge package rather than pip over in https://github.com/pangeo-data/pangeo-docker-images/pull/433

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by davidbrochart** [comment]
We want https://github.com/conda-forge/xarray_leaflet-feedstock/pull/22 instead, but it needs https://github.com/conda-forge/staged-recipes/pull/21758.

**Comment by davidbrochart** [comment]
@scottyhq xarray-leaflet v0.2.3 has been released.
